# Generated by Django 5.0.3 on 2024-04-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('pcid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pcname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('pcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('compid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('compdesc', models.CharField(max_length=500)),
                ('compdt', models.DateField()),
                ('status', models.CharField(default='open', max_length=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
    ]
