# Generated by Django 3.2.21 on 2024-05-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='compdt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ordid', models.IntegerField(primary_key=True, serialize=False)),
                ('orddt', models.DateField()),
                ('amount', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
    ]
